### PR TITLE
Add ValueProvider for lazy parameter evaluation

### PR DESCRIPTION
**Pull request by mborst**
This allows for only evaluating parameter in case they are needed.

### CODE REVIEW

**Comment by dohse** [comment]
Weired. I did not get a notification for this pull request.

**Comment by mborst** [comment]
Thanks! :)

**Comment by mborst** [comment]
Any plans for a release?

**Comment by dohse** [comment]
Should be released.

**Comment by ctavan** [comment]
@dohse latest version according to https://www.npmjs.com/package/gunk is 1.0.2: 

screenshot 2017-05-16 09 10 46

Could you check again if publishing the package worked?

**Comment by ctavan** [comment]
[package.json](https://github.com/dohse/gunk/blob/master/package.json#L3) also still shows `1.0.2`

**Comment by dohse** [comment]
I published it to our internal registry by accident.

**Pull request merged**
